{{- if .Values.ssh.enabled  }}
{{- if .Values.ssh.private_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-private-key
data:
  ssh-private-key: |
    {{ .Values.ssh.private_key | b64enc | indent 4 }}
{{- end }}
{{- else }}
{{ fail "SSH private key not set. Set both .Values.ssh.enabled and .Values.ssh.private_key" }}
{{- end }}
